package entities;
// Generated May 12, 2018 11:43:56 AM by Hibernate Tools 5.3.0.Beta2

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int accountId;
	private String username;
	private String password;

	public Account() {
	}

	public Account(int accountId) {
		this.accountId = accountId;
	}

	public Account(int accountId, String username, String password) {
		this.accountId = accountId;
		this.username = username;
		this.password = password;
	}

	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
